// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD71woWA21TBxhbrmtuSp1ecS-HlkwUKLU',
    appId: '1:620099384375:web:7f39066649a4c18e293bb2',
    messagingSenderId: '620099384375',
    projectId: 'sleep-apena',
    authDomain: 'sleep-apena.firebaseapp.com',
    storageBucket: 'sleep-apena.firebasestorage.app',
    measurementId: 'G-0FTP70LE87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWq65H8fITkwB6EAVDOX_IjDx5RNwxzlw',
    appId: '1:620099384375:android:15a9f1c74668bd4e293bb2',
    messagingSenderId: '620099384375',
    projectId: 'sleep-apena',
    storageBucket: 'sleep-apena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAre8LQzFUDyIzhJx8WN4TFRve-nlbxJJE',
    appId: '1:620099384375:ios:1640856952bc6aa1293bb2',
    messagingSenderId: '620099384375',
    projectId: 'sleep-apena',
    storageBucket: 'sleep-apena.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAre8LQzFUDyIzhJx8WN4TFRve-nlbxJJE',
    appId: '1:620099384375:ios:1640856952bc6aa1293bb2',
    messagingSenderId: '620099384375',
    projectId: 'sleep-apena',
    storageBucket: 'sleep-apena.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD71woWA21TBxhbrmtuSp1ecS-HlkwUKLU',
    appId: '1:620099384375:web:48f9e8faa44e31e4293bb2',
    messagingSenderId: '620099384375',
    projectId: 'sleep-apena',
    authDomain: 'sleep-apena.firebaseapp.com',
    storageBucket: 'sleep-apena.firebasestorage.app',
    measurementId: 'G-JDCPM83N5B',
  );

}